name: "Development Workflow"

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "development" ]
  # schedule:
    # - cron: '41 4 * * 3'

jobs:
  build-and-install-deps:
    name: Build Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Dependencies
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-deps
        with:
          path: ./client/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Could not find cache, Creating
        continue-on-error: true
        run: cd client && npm install
  lint:
    needs: build-and-install-deps
    name: ESLint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
     
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Load Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-deps
        with:
          path: ./client/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
      - name: Run ESLint
        run: cd client && npm run lint
  format-check:
    needs: [ build-and-install-deps ]
    name: Format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Load Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-deps
        with:
          path: ./client/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
      - name: Run Format Check
        run: cd client && npm run format:check
  build:
    needs: [build-and-install-deps]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Load Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-deps
      with:
        path: ./client/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
    - name: Build
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"
      run: cd client && npm run build
    - name: Upload Build artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Build artifacts
        path: ./client/dist/
      
  test:
    needs: [build-and-install-deps]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Load Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-deps
      with:
        path: ./client/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
    - name: Build
      run: cd client && npm run test:cov
      
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
